# Generated by Django 6.0.4 on 2026-06-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeinvitetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRequest',
        ),
    ]
