# Generated by Django 6.0.4 on 2026-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_branch_attendance_check_in_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_longitude',
        ),
    ]
