# Generated by Django 6.0.4 on 2026-06-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeesequence_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhaar'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('RESUME', 'Resume'), ('OFFER', 'Offer Letter'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
